### ISSUE TITLE
Level transitions

### ISSUE THREAD

**Issue by T4g1** [T4g1/jamcraft4#27]
Upon game start: Player spawns in a room with a single crafting station.
When level is generated, a portails/door open leading to the dungeon start
When the dungeon is over, exit portal get the player back to that room.
Upon entering the room, next level is generated,
and so on until end of the game

**Comment by delCatta** [comment]
Pushed to Spawning branch.

**Comment by T4g1** [comment]
Use fixed tag, dont close issues until they are merged in master
